name: Deploy to Deno Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install deployctl
        run: |
          deno install -A -f --unstable https://deno.land/x/deploy/deployctl.ts

      - name: Cache Deno dependencies
        run: deno cache main.js

      - name: Deploy to Deno
        env:
          DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}
        run: |
          deployctl deploy --project=mizuumi-shiritori-a-78 main.js
