name: Deploy to Deno Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x

    - name: Deploy to Deno Deploy
      run: |
        deno deploy --project=<YOUR_PROJECT_NAME> --entrypoint=main.js
      env:
        DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}
